--https://www.hackerrank.com/challenges/weather-observation-station-5
SELECT TOP 1 CITY, DATALENGTH(CITY) FROM STATION
ORDER BY DATALENGTH(CITY), CITY ASC 
SELECT TOP 1 CITY, DATALENGTH(CITY) FROM STATION
ORDER BY DATALENGTH(CITY) DESC, CITY ASC